### ISSUE TITLE
AnimeWatch doesn't load the selected video

### ISSUE THREAD

**Issue by SethBarberee** [kanishka-linux/AnimeWatch#2]
So I've tried this as normal user and root to run AnimeWatch to watch any episode of anime but it doesn't load the video after I select it. All the columns disappear, leaving just the background of the selected anime that I want to watch.

Found this at the end of running python3 -B animewatch.py
`I'm byte
[<select id="selectQuality"><option value="aHR0cHM6Ly9yZWRpcmVjdG9yLmdvb2dsZXZpZGVvLmNvbS92aWRlb3BsYXliYWNrP3JlcXVpcmVzc2w9eWVzJmlkPWEzYjk4MzAyNmFiNDcwNGUmaXRhZz0zNyZzb3VyY2U9d2ViZHJpdmUmYXBwPXRleG1leCZpcD0yMDAxOjE5ZjA6NjAwMDo5YWQ0OjU0MDA6ZmY6ZmUyMDo2NmVjJmlwYml0cz0zMiZleHBpcmU9MTQ2NDYzMzI3MCZzcGFyYW1zPXJlcXVpcmVzc2wsaWQsaXRhZyxzb3VyY2UsaXAsaXBiaXRzLGV4cGlyZSZzaWduYXR1cmU9OTE5RTc4MDYzOEI5OUE0M0NBREQ4NkU4NjA1MzdBMTZBMUQwQ0RENi4yMkM1NkE0M0VFQUE4Q0NDOTVFRUQyREJDQUIzMDlBMjI1NzFERkJCJmtleT1jazImbW09MzAmbW49c24tYTVtZWtuN2smbXM9bnh1Jm10PTE0NjQ2MTg3ODQmbXY9bSZuaD1JZ3B3Y2pBeUxteGhlREF5S2dreE1qY3VNQzR3TGpFJnBsPTM4">1080p</option><option selected="" value="aHR0cHM6Ly9yZWRpcmVjdG9yLmdvb2dsZXZpZGVvLmNvbS92aWRlb3BsYXliYWNrP3JlcXVpcmVzc2w9eWVzJmlkPWEzYjk4MzAyNmFiNDcwNGUmaXRhZz0yMiZzb3VyY2U9d2ViZHJpdmUmYXBwPXRleG1leCZpcD0yMDAxOjE5ZjA6NjAwMDo5YWQ0OjU0MDA6ZmY6ZmUyMDo2NmVjJmlwYml0cz0zMiZleHBpcmU9MTQ2NDYzMzI3MCZzcGFyYW1zPXJlcXVpcmVzc2wsaWQsaXRhZyxzb3VyY2UsaXAsaXBiaXRzLGV4cGlyZSZzaWduYXR1cmU9Qjg3RjJDOEI4MEVFNTlGQjA1NTg2QjBBNUMyNjdEOUEzNzVCMUE3My41QTNENjMwNjIxOEZGNEFEOTg3RkYxMjlEMjU1MTA4RTA4RTk1RjREJmtleT1jazImbW09MzAmbW49c24tYTVtZWtuN2smbXM9bnh1Jm10PTE0NjQ2MTg3ODQmbXY9bSZuaD1JZ3B3Y2pBeUxteGhlREF5S2dreE1qY3VNQzR3TGpFJnBsPTM4">720p</option><option value="aHR0cHM6Ly9yZWRpcmVjdG9yLmdvb2dsZXZpZGVvLmNvbS92aWRlb3BsYXliYWNrP3JlcXVpcmVzc2w9eWVzJmlkPWEzYjk4MzAyNmFiNDcwNGUmaXRhZz01OSZzb3VyY2U9d2ViZHJpdmUmYXBwPXRleG1leCZpcD0yMDAxOjE5ZjA6NjAwMDo5YWQ0OjU0MDA6ZmY6ZmUyMDo2NmVjJmlwYml0cz0zMiZleHBpcmU9MTQ2NDYzMzI3MCZzcGFyYW1zPXJlcXVpcmVzc2wsaWQsaXRhZyxzb3VyY2UsaXAsaXBiaXRzLGV4cGlyZSZzaWduYXR1cmU9NkJEN0UwNkVBQUY5OTkyQkM2NEJBM0NDRDBFM0E5RTNFNkE4MENCNS4zMDQyOEU3NTRGREVFOUY2Rjg5MjhGQUMyRTA2QkVGQjBGOTAwRTBCJmtleT1jazImbW09MzAmbW49c24tYTVtZWtuN2smbXM9bnh1Jm10PTE0NjQ2MTg3ODQmbXY9bSZuaD1JZ3B3Y2pBeUxteGhlREF5S2dreE1qY3VNQzR3TGpFJnBsPTM4">480p</option><option value="aHR0cHM6Ly9yZWRpcmVjdG9yLmdvb2dsZXZpZGVvLmNvbS92aWRlb3BsYXliYWNrP3JlcXVpcmVzc2w9eWVzJmlkPWEzYjk4MzAyNmFiNDcwNGUmaXRhZz0xOCZzb3VyY2U9d2ViZHJpdmUmYXBwPXRleG1leCZpcD0yMDAxOjE5ZjA6NjAwMDo5YWQ0OjU0MDA6ZmY6ZmUyMDo2NmVjJmlwYml0cz0zMiZleHBpcmU9MTQ2NDYzMzI3MCZzcGFyYW1zPXJlcXVpcmVzc2wsaWQsaXRhZyxzb3VyY2UsaXAsaXBiaXRzLGV4cGlyZSZzaWduYXR1cmU9NEQ1NjBFM0NCMkM3NEQ3OUNCQzFCOEZBQkUyNEZFNUVFQUY3RDc3Ny4zRUQ2QzBGRUI5NDlFQTE1OEQzQ0ZDODIwNkEyRkZGQjg0MjY3MEM3JmtleT1jazImbW09MzAmbW49c24tYTVtZWtuN2smbXM9bnh1Jm10PTE0NjQ2MTg3ODQmbXY9bSZuaD1JZ3B3Y2pBeUxteGhlREF5S2dreE1qY3VNQzR3TGpFJnBsPTM4">360p</option></select>]
['https://redirector.googlevideo.com/videoplayback?requiressl=yes&id=a3b983026ab4704e&itag=37&source=webdrive&app=texmex&ip=2001:19f0:6000:9ad4:5400:ff:fe20:66ec&ipbits=32&expire=1464633270&sparams=requiressl,id,itag,source,ip,ipbits,expire&signature=919E780638B99A43CADD86E860537A16A1D0CDD6.22C56A43EEAA8CCC95EED2DBCAB309A22571DFBB&key=ck2&mm=30&mn=sn-a5mekn7k&ms=nxu&mt=1464618784&mv=m&nh=IgpwcjAyLmxheDAyKgkxMjcuMC4wLjE&pl=38', 'https://redirector.googlevideo.com/videoplayback?requiressl=yes&id=a3b983026ab4704e&itag=22&source=webdrive&app=texmex&ip=2001:19f0:6000:9ad4:5400:ff:fe20:66ec&ipbits=32&expire=1464633270&sparams=requiressl,id,itag,source,ip,ipbits,expire&signature=B87F2C8B80EE59FB05586B0A5C267D9A375B1A73.5A3D6306218FF4AD987FF129D255108E08E95F4D&key=ck2&mm=30&mn=sn-a5mekn7k&ms=nxu&mt=1464618784&mv=m&nh=IgpwcjAyLmxheDAyKgkxMjcuMC4wLjE&pl=38', 'https://redirector.googlevideo.com/videoplayback?requiressl=yes&id=a3b983026ab4704e&itag=59&source=webdrive&app=texmex&ip=2001:19f0:6000:9ad4:5400:ff:fe20:66ec&ipbits=32&expire=1464633270&sparams=requiressl,id,itag,source,ip,ipbits,expire&signature=6BD7E06EAAF9992BC64BA3CCD0E3A9E3E6A80CB5.30428E754FDEE9F6F8928FAC2E06BEFB0F900E0B&key=ck2&mm=30&mn=sn-a5mekn7k&ms=nxu&mt=1464618784&mv=m&nh=IgpwcjAyLmxheDAyKgkxMjcuMC4wLjE&pl=38', 'https://redirector.googlevideo.com/videoplayback?requiressl=yes&id=a3b983026ab4704e&itag=18&source=webdrive&app=texmex&ip=2001:19f0:6000:9ad4:5400:ff:fe20:66ec&ipbits=32&expire=1464633270&sparams=requiressl,id,itag,source,ip,ipbits,expire&signature=4D560E3CB2C74D79CBC1B8FABE24FE5EEAF7D777.3ED6C0FEB949EA158D3CFC8206A2FFFB842670C7&key=ck2&mm=30&mn=sn-a5mekn7k&ms=nxu&mt=1464618784&mv=m&nh=IgpwcjAyLmxheDAyKgkxMjcuMC4wLjE&pl=38']
https://redirector.googlevideo.com/videoplayback?requiressl=yes&id=a3b983026ab4704e&itag=18&source=webdrive&app=texmex&ip=2001:19f0:6000:9ad4:5400:ff:fe20:66ec&ipbits=32&expire=1464633270&sparams=requiressl,id,itag,source,ip,ipbits,expire&signature=4D560E3CB2C74D79CBC1B8FABE24FE5EEAF7D777.3ED6C0FEB949EA158D3CFC8206A2FFFB842670C7&key=ck2&mm=30&mn=sn-a5mekn7k&ms=nxu&mt=1464618784&mv=m&nh=IgpwcjAyLmxheDAyKgkxMjcuMC4wLjE&pl=38
https://redirector.googlevideo.com/videoplayback?requiressl=yes&id=a3b983026ab4704e&itag=18&source=webdrive&app=texmex&ip=2001:19f0:6000:9ad4:5400:ff:fe20:66ec&ipbits=32&expire=1464633270&sparams=requiressl,id,itag,source,ip,ipbits,expire&signature=4D560E3CB2C74D79CBC1B8FABE24FE5EEAF7D777.3ED6C0FEB949EA158D3CFC8206A2FFFB842670C7&key=ck2&mm=30&mn=sn-a5mekn7k&ms=nxu&mt=1464618784&mv=m&nh=IgpwcjAyLmxheDAyKgkxMjcuMC4wLjE&pl=38#-I
`

**Comment by kanishka-linux** [comment]
Hi sorry for late reply,
AnimeWatch is working fine on my machine. Therefore I can't say for sure what could be a problem.
It might be a problem with source website. Try changing mpv to mplayer or some other external player.
And do not run the command using root privileges, it can be risky. Root privileges are not required for this programme. Please check once again working of the application.

**Comment by SethBarberee** [comment]
Just updated AnimeWatch today and it did start working again. It could have been the source website because it was done for a while and mpv then kept goofing up. Thank you for this great program!
