### ISSUE TITLE
Make 64bit deb for ubuntu

### ISSUE THREAD

**Issue by wingedonezero** [kanishka-linux/AnimeWatch#3]
I want to try and install but it requires a i386 mpv can you make a build for 64bit most people use 64bit nowadays. I would appriciate it.

**Comment by kanishka-linux** [comment]
Hello wingedonezero,
Thanks for pointing out the problem. The programme is written in platform independent manner, hence it should work everywhere as long as it's gnu/linux based system. I've just made changes in control file to add support for all architecture and rebuild the .deb package and uploaded it. You can download from release section or Debian-Stable-Package directory. I've tested it on xubuntu 14.04.
