### ISSUE TITLE
Animewatch 2.9.0 doesn't open (has error)

### ISSUE THREAD

**Issue by SethBarberee** [kanishka-linux/AnimeWatch#5]
Error log:
`Traceback (most recent call last):
  File "/usr/share/AnimeWatch/animeWatch.py", line 76, in <module>
    from stream import ThreadServer,TorrentThread,get_torrent_info,set_torrent_info,get_torrent_info_magnet
  File "/usr/share/AnimeWatch/stream.py", line 26, in <module>
    import libtorrent as lt
ImportError: /usr/lib/libboost_python.so.1.61.0: undefined symbol: PyClass_Type
`

**Comment by kanishka-linux** [comment]
python3 bindings for libtorrent are broken in arch. A bug report has been filed already. You can read about the bug and temporary solution in the post https://bugs.archlinux.org/task/50745. I've already written about the bug in arch linux forum. After installing libtorrent from PKGBUILD mentioned in the bug report, remove addons directory and config.txt file manually before relaunching the application.

**Comment by kanishka-linux** [comment]
I've also mentioned about it in the dependencies and installation section of the README.

**Comment by kanishka-linux** [comment]
The latest update on Arch fixed the issue of broken python3 bindings for libtorrent. Therefore I'm closing the issue. As a precaution I've added code to disable torrent streaming feature in case something like this happens again, which will prevent the application from crashing.
