### ISSUE TITLE
Kissanime Domain Change

### ISSUE THREAD

**Issue by SethBarberee** [kanishka-linux/AnimeWatch#6]
They migrated over to http://kissanime.io because of server issues. http://kissanime.to is now defunt

**Comment by kanishka-linux** [comment]
Currently, their site is redirecting to .ru domain, which I think is a legitimate site. For more info please read [the issue here.](https://www.reddit.com/r/KissAnime/comments/5iy7oy/kissanime_admin_this_is_what_happen_to_kiss_sites/)
